server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
  application:
    name: user   
logging:
  level:
    com.mapper.UserMapper: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/    
    
    
    
    
    
    
    
    